/**
 * useLanguage — global language access hook.
 *
 * Reads the user's language preference from ChatContext (→ localStorage).
 * Provides:
 *  - `language`: current AppLanguage
 *  - `setLanguage(lang)`: update language globally
 *  - `t(key)`: translate a known UI string key to the user's language
 */

"use client";

import { useChat } from "../components/chat-context";
import type { AppLanguage } from "../lib/types";

// ── Language-Aware UI Strings ─────────────────────────────────────────────
// These are the hardcoded English status messages used across pages.
// The map provides translations for all 9 supported languages.

const UI_STRINGS: Record<string, Record<AppLanguage, string>> = {
  "search.loading": {
    de: "Suche...",
    en: "Searching...",
    tr: "Arşiv taranıyor...",
    ar: "جارٍ مسح الأرشيف...",
    fr: "Recherche...",
    es: "Buscando...",
    pl: "Skanowanie archiwów...",
    uk: "Сканування архіву...",
    ru: "Поиск...",
  },
  "search.results_count": {
    de: "{n} Gesetze gefunden",
    en: "{n} Statutes Retrieved",
    tr: "{n} Yasa Bulundu",
    ar: "تم استرداد {n} قانونًا",
    fr: "{n} Lois trouvées",
    es: "{n} Leyes encontradas",
    pl: "Znaleziono {n} ustaw",
    uk: "Знайдено {n} законів",
    ru: "Найдено {n} законов",
  },
  "search.empty": {
    de: "Keine Gesetze gefunden.",
    en: "No statutes found matching the inquiry parameters.",
    tr: "Sorgu kriterlerine uygun yasa bulunamadı.",
    ar: "لم يتم العثور على قوانين تطابق معايير الاستعلام.",
    fr: "Aucune loi trouvée correspondant aux paramètres.",
    es: "No se encontraron leyes que coincidan.",
    pl: "Nie znaleziono pasujących ustaw.",
    uk: "Не знайдено законів, що відповідають параметрам пошуку.",
    ru: "Не найдено законов, соответствующих параметрам запроса.",
  },
  "search.error": {
    de: "Fehler bei der Suche",
    en: "Failed to fetch search results.",
    tr: "Arama sonuçları alınamadı.",
    ar: "فشل في جلب نتائج البحث.",
    fr: "Échec de la récupération des résultats.",
    es: "Error al obtener resultados.",
    pl: "Nie udało się pobrać wyników wyszukiwania.",
    uk: "Не вдалося отримати результати пошуку.",
    ru: "Не удалось получить результаты поиска.",
  },
  "laws.loading": {
    de: "Entschlüssele Gesetz...",
    en: "Decrypting Statute...",
    tr: "Yasa çözülüyor...",
    ar: "جارٍ فك تشفير القانون...",
    fr: "Déchiffrement de la loi...",
    es: "Descifrando ley...",
    pl: "Odszyfrowywanie ustawy...",
    uk: "Розшифрування закону...",
    ru: "Расшифровка закона...",
  },
  "laws.not_found": {
    de: "Gesetz nicht gefunden",
    en: "Law not found or could not be loaded.",
    tr: "Yasa bulunamadı veya yüklenemedi.",
    ar: "لم يتم العثور على القانون أو تعذر تحميله.",
    fr: "Loi introuvable ou impossible à charger.",
    es: "Ley no encontrada o no se pudo cargar.",
    pl: "Nie znaleziono ustawy lub nie można załadować.",
    uk: "Закон не знайдено або не вдалося завантажити.",
    ru: "Закон не найден или не может быть загружен.",
  },
  "laws.norms_empty": {
    de: "Gesetzesabschnitte nicht im neuronalen Speicher indiziert.",
    en: "Statutory fragments not currently indexed in neural memory.",
    tr: "Yasa parçaları sinirsel bellekte indekslenmemiş.",
    ar: "أجزاء القانون غير مفهرسة حاليًا في الذاكرة العصبية.",
    fr: "Fragments législatifs non indexés dans la mémoire neuronale.",
    es: "Fragmentos legales no indexados en la memoria neuronal.",
    pl: "Fragmenty ustaw nie są obecnie indeksowane w pamięci neuronowej.",
    uk: "Фрагменти законів наразі не індексовані в нейронній пам'яті.",
    ru: "Фрагменты законов в настоящее время не проиндексированы в нейронной памяти.",
  },
  "search.awaiting": {
    de: "Warte auf Anfrage",
    en: "Awaiting Inquiry",
    tr: "Sorgu Bekleniyor",
    ar: "في انتظار الاستعلام",
    fr: "En attente de requête",
    es: "Esperando consulta",
    pl: "Oczekiwanie na zapytanie",
    uk: "Очікування запиту",
    ru: "Ожидание запроса",
  },
  "search.init": {
    de: "Initialisiere Suche...",
    en: "Initializing Search Environment...",
    tr: "Arama Ortamı Başlatılıyor...",
    ar: "جارٍ تهيئة بيئة البحث...",
    fr: "Initialisation de l'environnement de recherche...",
    es: "Inicializando entorno de búsqueda...",
    pl: "Inicjowanie środowiska wyszukiwania...",
    uk: "Ініціалізація середовища пошуку...",
    ru: "Инициализация среды поиска...",
  },
  "guidance.loading": {
    de: "Analysiere Situation...",
    en: "Analyzing Situation...",
    tr: "Durum analiz ediliyor...",
    ar: "جارٍ تحليل الموقف...",
    fr: "Analyse de la situation...",
    es: "Analizando situación...",
    pl: "Analizowanie sytuacji...",
    uk: "Аналіз ситуації...",
    ru: "Анализ ситуации...",
  },
  "common.error": {
    de: "Betriebsfehler",
    en: "Operational Error",
    tr: "Operasyonel Hata",
    ar: "خطأ تشغيلي",
    fr: "Erreur opérationnelle",
    es: "Error operativo",
    pl: "Błąd operacyjny",
    uk: "Операційна помилка",
    ru: "Операционная ошибка",
  },

  // ── Navigation ────────────────────────────────────────────────────────────
  "nav.sign_in": {
    de: "Anmelden",
    en: "Sign In",
    tr: "Giriş Yap",
    ar: "تسجيل الدخول",
    fr: "Se connecter",
    es: "Iniciar sesión",
    pl: "Zaloguj się",
    uk: "Увійти",
    ru: "Войти",
  },
  "nav.sign_out": {
    de: "Abmelden",
    en: "Sign Out",
    tr: "Çıkış Yap",
    ar: "تسجيل الخروج",
    fr: "Se déconnecter",
    es: "Cerrar sesión",
    pl: "Wyloguj się",
    uk: "Вийти",
    ru: "Выйти",
  },
  "nav.search": {
    de: "Suche",
    en: "Search",
    tr: "Arama",
    ar: "بحث",
    fr: "Rechercher",
    es: "Buscar",
    pl: "Szukaj",
    uk: "Пошук",
    ru: "Поиск",
  },
  "nav.guidance": {
    de: "Beratung",
    en: "Guidance",
    tr: "Rehberlik",
    ar: "إرشاد",
    fr: "Conseil",
    es: "Asesoría",
    pl: "Porada",
    uk: "Консультація",
    ru: "Консультация",
  },
  "nav.bookmarks": {
    de: "Lesezeichen",
    en: "Bookmarks",
    tr: "Yer İmleri",
    ar: "الإشارات المرجعية",
    fr: "Favoris",
    es: "Marcadores",
    pl: "Zakładki",
    uk: "Закладки",
    ru: "Закладки",
  },
  "nav.chat": {
    de: "Chat",
    en: "Chat",
    tr: "Sohbet",
    ar: "دردشة",
    fr: "Chat",
    es: "Chat",
    pl: "Czat",
    uk: "Чат",
    ru: "Чат",
  },
  "nav.settings": {
    de: "Einstellungen",
    en: "Settings",
    tr: "Ayarlar",
    ar: "الإعدادات",
    fr: "Paramètres",
    es: "Ajustes",
    pl: "Ustawienia",
    uk: "Налаштування",
    ru: "Настройки",
  },
  "nav.laws": {
    de: "Gesetze",
    en: "Laws",
    tr: "Yasalar",
    ar: "القوانين",
    fr: "Lois",
    es: "Leyes",
    pl: "Ustawy",
    uk: "Закони",
    ru: "Законы",
  },
  "nav.api_docs": {
    de: "API-Dokumentation",
    en: "API Docs",
    tr: "API Dokümanları",
    ar: "وثائق API",
    fr: "Documentation API",
    es: "Documentación API",
    pl: "Dokumentacja API",
    uk: "Документація API",
    ru: "Документация API",
  },

  // ── Footer ────────────────────────────────────────────────────────────────
  "footer.tagline": {
    de: "Sub lege libertas",
    en: "Sub lege libertas",
    tr: "Sub lege libertas",
    ar: "Sub lege libertas",
    fr: "Sub lege libertas",
    es: "Sub lege libertas",
    pl: "Sub lege libertas",
    uk: "Sub lege libertas",
    ru: "Sub lege libertas",
  },
  "footer.copyright": {
    de: "© 2026 German Law Vault — Offizielles Rechtsinformationssystem",
    en: "© 2026 German Law Vault — Official Legal Intelligence Repository",
    tr: "© 2026 German Law Vault — Resmî Hukuk Bilgi Sistemi",
    ar: "© 2026 خزانة القانون الألماني — مستودع الذكاء القانوني الرسمي",
    fr: "© 2026 German Law Vault — Système officiel d'information juridique",
    es: "© 2026 German Law Vault — Repositorio oficial de inteligencia legal",
    pl: "© 2026 German Law Vault — Oficjalne repozytorium wiedzy prawnej",
    uk: "© 2026 German Law Vault — Офіційне джерело правової інформації",
    ru: "© 2026 German Law Vault — Официальный правовой информационный ресурс",
  },

  // ── Auth Page ─────────────────────────────────────────────────────────────
  "auth.title": {
    de: "Willkommen",
    en: "Welcome",
    tr: "Hoş Geldiniz",
    ar: "مرحبًا",
    fr: "Bienvenue",
    es: "Bienvenido",
    pl: "Witamy",
    uk: "Ласкаво просимо",
    ru: "Добро пожаловать",
  },
  "auth.email": {
    de: "E-Mail",
    en: "Email",
    tr: "E-posta",
    ar: "البريد الإلكتروني",
    fr: "E-mail",
    es: "Correo electrónico",
    pl: "E-mail",
    uk: "Електронна пошта",
    ru: "Электронная почта",
  },
  "auth.password": {
    de: "Passwort",
    en: "Password",
    tr: "Şifre",
    ar: "كلمة المرور",
    fr: "Mot de passe",
    es: "Contraseña",
    pl: "Hasło",
    uk: "Пароль",
    ru: "Пароль",
  },
  "auth.sign_in_button": {
    de: "Anmelden",
    en: "Sign In",
    tr: "Giriş Yap",
    ar: "تسجيل الدخول",
    fr: "Se connecter",
    es: "Iniciar sesión",
    pl: "Zaloguj się",
    uk: "Увійти",
    ru: "Войти",
  },
  "auth.sign_up_button": {
    de: "Konto erstellen",
    en: "Create Account",
    tr: "Hesap Oluştur",
    ar: "إنشاء حساب",
    fr: "Créer un compte",
    es: "Crear cuenta",
    pl: "Utwórz konto",
    uk: "Створити обліковий запис",
    ru: "Создать аккаунт",
  },
  "auth.no_account": {
    de: "Noch kein Konto?",
    en: "Don't have an account?",
    tr: "Hesabınız yok mu?",
    ar: "ليس لديك حساب؟",
    fr: "Vous n'avez pas de compte?",
    es: "¿No tienes una cuenta?",
    pl: "Nie masz konta?",
    uk: "Немає облікового запису?",
    ru: "Нет аккаунта?",
  },
  "auth.has_account": {
    de: "Bereits ein Konto?",
    en: "Already have an account?",
    tr: "Zaten hesabınız var mı?",
    ar: "هل لديك حساب بالفعل؟",
    fr: "Vous avez déjà un compte?",
    es: "¿Ya tienes una cuenta?",
    pl: "Masz już konto?",
    uk: "Вже маєте обліковий запис?",
    ru: "Уже есть аккаунт?",
  },
  "auth.error_prefix": {
    de: "Fehler",
    en: "Error",
    tr: "Hata",
    ar: "خطأ",
    fr: "Erreur",
    es: "Error",
    pl: "Błąd",
    uk: "Помилка",
    ru: "Ошибка",
  },

  // ── Chat Page ─────────────────────────────────────────────────────────────
  "chat.title": {
    de: "Rechtsberater",
    en: "Legal Advisor",
    tr: "Hukuk Danışmanı",
    ar: "مستشار قانوني",
    fr: "Conseiller juridique",
    es: "Asesor legal",
    pl: "Doradca prawny",
    uk: "Юридичний консультант",
    ru: "Юридический консультант",
  },
  "chat.placeholder": {
    de: "Beschreiben Sie Ihre rechtliche Situation...",
    en: "Describe your legal situation...",
    tr: "Hukuki durumunuzu açıklayın...",
    ar: "صف وضعك القانوني...",
    fr: "Décrivez votre situation juridique...",
    es: "Describa su situación legal...",
    pl: "Opisz swoją sytuację prawną...",
    uk: "Опишіть свою правову ситуацію...",
    ru: "Опишите вашу правовую ситуацию...",
  },
  "chat.send": {
    de: "Senden",
    en: "Send",
    tr: "Gönder",
    ar: "إرسال",
    fr: "Envoyer",
    es: "Enviar",
    pl: "Wyślij",
    uk: "Надіслати",
    ru: "Отправить",
  },
  "chat.settings": {
    de: "Einstellungen",
    en: "Settings",
    tr: "Ayarlar",
    ar: "الإعدادات",
    fr: "Paramètres",
    es: "Ajustes",
    pl: "Ustawienia",
    uk: "Налаштування",
    ru: "Настройки",
  },
  "chat.local_offline": {
    de: "Lokaler Knoten offline",
    en: "Local Node Offline",
    tr: "Yerel Düğüm Çevrimdışı",
    ar: "العقدة المحلية غير متصلة",
    fr: "Nœud local hors ligne",
    es: "Nodo local desconectado",
    pl: "Lokalny węzeł offline",
    uk: "Локальний вузол не в мережі",
    ru: "Локальный узел не в сети",
  },
  "chat.startup_hint": {
    de: "Starten Sie Ollama und den Broker, um den lokalen KI-Modus zu aktivieren",
    en: "Start your local Ollama and broker to enable fully offline AI mode",
    tr: "Tamamen çevrimdışı AI modunu etkinleştirmek için yerel Ollama ve aracınızı başlatın",
    ar: "قم بتشغيل Ollama المحلي والوسيط لتفعيل وضع الذكاء الاصطناعي دون اتصال",
    fr: "Lancez Ollama et le broker pour activer le mode IA hors ligne",
    es: "Inicie su Ollama local y el broker para activar el modo IA sin conexión",
    pl: "Uruchom lokalnego Ollamę i brokera, aby włączyć w pełni offline tryb AI",
    uk: "Запустіть локальний Ollama та брокер для активації повністю офлайн-режиму AI",
    ru: "Запустите локальный Ollama и брокер для активации полностью офлайн-режима ИИ",
  },
  "chat.mode_basic": {
    de: "Basis",
    en: "Basic",
    tr: "Temel",
    ar: "أساسي",
    fr: "Basique",
    es: "Básico",
    pl: "Podstawowy",
    uk: "Базовий",
    ru: "Базовый",
  },
  "chat.mode_browser": {
    de: "Browser",
    en: "Browser",
    tr: "Tarayıcı",
    ar: "المتصفح",
    fr: "Navigateur",
    es: "Navegador",
    pl: "Przeglądarka",
    uk: "Браузер",
    ru: "Браузер",
  },
  "chat.mode_cloud": {
    de: "Cloud",
    en: "Cloud",
    tr: "Bulut",
    ar: "سحابة",
    fr: "Cloud",
    es: "Nube",
    pl: "Chmura",
    uk: "Хмара",
    ru: "Облако",
  },
  "chat.mode_local": {
    de: "Lokal",
    en: "Local",
    tr: "Yerel",
    ar: "محلي",
    fr: "Local",
    es: "Local",
    pl: "Lokalny",
    uk: "Локальний",
    ru: "Локальный",
  },

  // ── Bookmarks Page ────────────────────────────────────────────────────────
  "bookmarks.title": {
    de: "Meine Lesezeichen",
    en: "My Bookmarks",
    tr: "Yer İmlerim",
    ar: "إشاراتي المرجعية",
    fr: "Mes favoris",
    es: "Mis marcadores",
    pl: "Moje zakładki",
    uk: "Мої закладки",
    ru: "Мои закладки",
  },
  "bookmarks.empty": {
    de: "Noch keine Lesezeichen",
    en: "No bookmarks yet",
    tr: "Henüz yer imi yok",
    ar: "لا توجد إشارات مرجعية بعد",
    fr: "Pas encore de favoris",
    es: "Aún no hay marcadores",
    pl: "Brak zakładek",
    uk: "Ще немає закладок",
    ru: "Еще нет закладок",
  },
  "bookmarks.new_folder": {
    de: "Neuer Ordner",
    en: "New Folder",
    tr: "Yeni Klasör",
    ar: "مجلد جديد",
    fr: "Nouveau dossier",
    es: "Nueva carpeta",
    pl: "Nowy folder",
    uk: "Нова папка",
    ru: "Новая папка",
  },
  "bookmarks.delete_folder": {
    de: "Ordner löschen",
    en: "Delete Folder",
    tr: "Klasörü Sil",
    ar: "حذف المجلد",
    fr: "Supprimer le dossier",
    es: "Eliminar carpeta",
    pl: "Usuń folder",
    uk: "Видалити папку",
    ru: "Удалить папку",
  },

  // ── Guidance Page ─────────────────────────────────────────────────────────
  "guidance.title": {
    de: "Rechtsberatung",
    en: "Legal Guidance",
    tr: "Hukuki Rehberlik",
    ar: "إرشاد قانوني",
    fr: "Conseil juridique",
    es: "Asesoría legal",
    pl: "Porada prawna",
    uk: "Юридична консультація",
    ru: "Юридическая консультация",
  },
  "guidance.describe": {
    de: "Beschreiben Sie Ihre Situation",
    en: "Describe Your Situation",
    tr: "Durumunuzu Açıklayın",
    ar: "صف وضعك",
    fr: "Décrivez votre situation",
    es: "Describa su situación",
    pl: "Opisz swoją sytuację",
    uk: "Опишіть свою ситуацію",
    ru: "Опишите вашу ситуацию",
  },
  "guidance.analyze": {
    de: "Analysieren",
    en: "Analyze",
    tr: "Analiz Et",
    ar: "تحليل",
    fr: "Analyser",
    es: "Analizar",
    pl: "Analizuj",
    uk: "Проаналізувати",
    ru: "Анализировать",
  },
  "guidance.no_folder": {
    de: "Kein Ordner ausgewählt",
    en: "No folder selected",
    tr: "Klasör seçilmedi",
    ar: "لم يتم تحديد مجلد",
    fr: "Aucun dossier sélectionné",
    es: "Ninguna carpeta seleccionada",
    pl: "Nie wybrano folderu",
    uk: "Папку не вибрано",
    ru: "Папка не выбрана",
  },
  "guidance.history": {
    de: "Verlauf",
    en: "History",
    tr: "Geçmiş",
    ar: "السجل",
    fr: "Historique",
    es: "Historial",
    pl: "Historia",
    uk: "Історія",
    ru: "История",
  },

  // ── Settings Page ─────────────────────────────────────────────────────────
  "settings.title": {
    de: "Einstellungen",
    en: "Settings",
    tr: "Ayarlar",
    ar: "الإعدادات",
    fr: "Paramètres",
    es: "Ajustes",
    pl: "Ustawienia",
    uk: "Налаштування",
    ru: "Настройки",
  },
  "settings.api_key": {
    de: "API-Schlüssel",
    en: "API Key",
    tr: "API Anahtarı",
    ar: "مفتاح API",
    fr: "Clé API",
    es: "Clave API",
    pl: "Klucz API",
    uk: "Ключ API",
    ru: "Ключ API",
  },
  "settings.save": {
    de: "Speichern",
    en: "Save",
    tr: "Kaydet",
    ar: "حفظ",
    fr: "Enregistrer",
    es: "Guardar",
    pl: "Zapisz",
    uk: "Зберегти",
    ru: "Сохранить",
  },
  "settings.remove": {
    de: "Entfernen",
    en: "Remove",
    tr: "Kaldır",
    ar: "إزالة",
    fr: "Supprimer",
    es: "Eliminar",
    pl: "Usuń",
    uk: "Видалити",
    ru: "Удалить",
  },
  "settings.provider": {
    de: "KI-Anbieter",
    en: "AI Provider",
    tr: "AI Sağlayıcı",
    ar: "موفر الذكاء الاصطناعي",
    fr: "Fournisseur d'IA",
    es: "Proveedor de IA",
    pl: "Dostawca AI",
    uk: "Постачальник AI",
    ru: "Поставщик ИИ",
  },
  "settings.model": {
    de: "Modell",
    en: "Model",
    tr: "Model",
    ar: "النموذج",
    fr: "Modèle",
    es: "Modelo",
    pl: "Model",
    uk: "Модель",
    ru: "Модель",
  },

  // ── Search Page ───────────────────────────────────────────────────────────
  "search.placeholder": {
    de: "Deutsche Gesetze durchsuchen...",
    en: "Search German laws...",
    tr: "Alman yasalarında ara...",
    ar: "ابحث في القوانين الألمانية...",
    fr: "Rechercher dans les lois allemandes...",
    es: "Buscar leyes alemanas...",
    pl: "Szukaj w niemieckich ustawach...",
    uk: "Пошук німецьких законів...",
    ru: "Поиск немецких законов...",
  },
  "search.no_results": {
    de: "Keine Ergebnisse gefunden",
    en: "No results found",
    tr: "Sonuç bulunamadı",
    ar: "لم يتم العثور على نتائج",
    fr: "Aucun résultat trouvé",
    es: "No se encontraron resultados",
    pl: "Nie znaleziono wyników",
    uk: "Результатів не знайдено",
    ru: "Результаты не найдены",
  },
};

/**
 * useLanguage — reads/writes global language from ChatContext.
 * Provides a `t(key, vars?)` function for translated UI strings.
 */
export function useLanguage() {
  const { settings, updateSettings } = useChat();
  const language = settings.language || "en";

  const setLanguage = (lang: AppLanguage) => {
    updateSettings({ language: lang });
  };

  /**
   * Translate a UI string key to the current language.
   * Supports `{n}` style variable interpolation.
   * Falls back to English if the key or language is not found.
   *
   * @example
   *   t("search.results_count", { n: 12 }) // → "12 Statutes Retrieved"
   */
  const t = (key: string, vars?: Record<string, string | number>): string => {
    const translations = UI_STRINGS[key];
    if (!translations) return key;

    let text = translations[language] || translations["en"] || key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        text = text.replace(`{${k}}`, String(v));
      }
    }
    return text;
  };

  return { language, setLanguage, t };
}
