"use client";

import { useState, useEffect, useCallback, startTransition } from "react";
import { Languages, Loader2, ChevronDown } from "lucide-react";
import {
  AppLanguage,
  NormExplanation,
  ChatSettings,
  DEFAULT_CHAT_SETTINGS,
  LANGUAGE_NAMES,
} from "../lib/types";
import { toast } from "sonner";
import { translateViaQwen } from "../lib/translate-via-qwen";
import { FeatureGate } from "./feature-gate";
import { useLanguage } from "../hooks/useLanguage";

const STORAGE_KEY = "glv_chat_settings";

interface NormViewerProps {
  normId: string;
  lawKey: string;
  title: string;
  content: string;
}

export default function NormViewer({
  normId,
  lawKey,
  title,
  content,
}: NormViewerProps) {
  const { t } = useLanguage();
  const [expanded, setExpanded] = useState(false);
  const [explanation, setExplanation] = useState<NormExplanation | null>(null);
  const [explaining, setExplaining] = useState(false);
  const [showGerman, setShowGerman] = useState(false);
  const [settings, setSettings] = useState<ChatSettings>(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        return { ...DEFAULT_CHAT_SETTINGS, ...JSON.parse(raw) };
      }
    } catch {}
    return DEFAULT_CHAT_SETTINGS;
  });
  const {
    mode,
    language: langSetting,
    brokerUrl,
    ollamaModel,
    provider,
    model,
    customEndpoint,
    ollamaParams,
  } = settings;
  const fetchExplanation = useCallback(async () => {
    if (explanation || explaining) return;
    setExplaining(true);
    try {
      if (mode === "local") {
        // CLIENT-SIDE EXPLAIN FOR LOCAL MODE
        const langName = LANGUAGE_NAMES[langSetting] || "English";
        const explainPrompt = `Explain this German law section. Respond in ${langName}.\n\nGerman text: ${content}\n\nReturn STRICT JSON with these exact fields:\n{\n  "translation": "accurate legal translation of the German text",\n  "summary": "what this means in simple terms in the user's language",\n  "implications": "what this means practically for the person involved",\n  "next_steps": "concrete recommended actions"\n}`;

        const brokerRes = await fetch(`${brokerUrl}/api/chat`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            message: explainPrompt,
            context: content,
            model: ollamaModel || undefined,
            language: langName,
            temperature: 0.3,
            max_tokens: 2048,
          }),
        });

        if (!brokerRes.ok) throw new Error("Local broker failure");
        const localData = await brokerRes.json();

        let jsonStr = localData.response.trim();
        const codeBlockMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)```/);
        if (codeBlockMatch) jsonStr = codeBlockMatch[1].trim();

        let parsed;
        try {
          parsed = JSON.parse(jsonStr);
        } catch {
          parsed = {
            translation: jsonStr,
            summary: jsonStr,
            implications: jsonStr,
            next_steps: jsonStr,
          };
        }

        setExplanation({
          norm_id: normId,
          law_key: lawKey,
          law_title: title,
          lang: settings.language as AppLanguage,
          translation: parsed.translation || "",
          summary: parsed.summary || "",
          implications: parsed.implications || "",
          next_steps: parsed.next_steps || "",
          disclaimer: "Generated by Local AI.",
        });
        return;
      }

      // BROWSER AI MODE — translate via cached Qwen model (no API key, no extra downloads)
      if (mode === "browser") {
        const langName = LANGUAGE_NAMES[langSetting] || "English";
        let translation = "";
        try {
          translation = await translateViaQwen(content, langName);
        } catch {
          translation = content; // fall back to raw German if worker fails
        }
        setExplanation({
          norm_id: normId,
          law_key: lawKey,
          law_title: title,
          lang: langSetting as AppLanguage,
          translation: translation,
          summary: `Browser AI translation (${langName}) — not legally binding.`,
          implications:
            "See a licensed German attorney (Rechtsanwalt) for legally binding advice on your specific situation.",
          next_steps: "Consult a Rechtsanwalt for your specific situation.",
          disclaimer: `Generated by browser AI (${langName}), client-side.`,
        });
        return;
      }

      // BASIC MODE — translate via cached Qwen model
      if (mode === "basic") {
        const langName = LANGUAGE_NAMES[langSetting] || "English";
        let translation = "";
        try {
          translation = await translateViaQwen(content, langName);
        } catch {
          translation = content; // fall back to raw German if worker fails
        }
        setExplanation({
          norm_id: normId,
          law_key: lawKey,
          law_title: title,
          lang: langSetting as AppLanguage,
          translation: translation,
          summary: `Browser translation (${langName}) — not legally binding.`,
          implications:
            "See a licensed German attorney (Rechtsanwalt) for legally binding advice on your specific situation.",
          next_steps: "Consult a Rechtsanwalt for your specific situation.",
          disclaimer: `Generated by browser AI (${langName}), client-side.`,
        });
        return;
      }

      // CLOUD MODES
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          normId,
          lawKey,
          lawTitle: title,
          content,
          lang: langSetting,
          mode,
          provider,
          model,
          customEndpoint,
          brokerUrl,
          ollamaModel,
          ollamaParams,
        }),
      });
      if (!res.ok) throw new Error("Explanation failed");
      const data = (await res.json()) as NormExplanation;
      setExplanation(data);
    } catch (err) {
      console.error("Norm explain failed:", err);
      if (mode === "local") {
        toast.error(
          "Local AI unavailable. Check if Ollama is running and the broker URL is correct.",
        );
      } else if (mode === "browser" || mode === "basic") {
        toast.error(
          "Browser AI translation failed. The translation model may still be downloading.",
        );
      } else {
        toast.error("Explanation failed. Check settings.");
      }
    } finally {
      setExplaining(false);
    }
  }, [
    explanation,
    explaining,
    mode,
    langSetting,
    brokerUrl,
    ollamaModel,
    normId,
    lawKey,
    title,
    content,
  ]);

  // Auto-fetch translation when section is expanded and AI mode is active
  useEffect(() => {
    if (expanded && mode !== "basic" && !explanation && !explaining) {
      fetchExplanation();
    }
  }, [expanded, mode, explanation, explaining, fetchExplanation]);

  return (
    <div className="premium-card overflow-hidden mb-6 group/norm border-white/5 bg-zinc-950/20 edge-glow-electric">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between p-8 text-left hover:bg-white/[0.01] transition-all duration-500 relative"
      >
        <div className="flex-1">
          <span className="text-accent-gold-body font-black mr-6 text-xs tracking-[0.3em] uppercase opacity-60">
            {t("norm.section", { id: normId })}
          </span>
          <span className="font-serif font-bold text-white text-xl tracking-tight">
            {title}
          </span>
        </div>
        <div className="flex items-center gap-6">
          <div
            className={`p-2 transition-transform duration-500 ${expanded ? "rotate-180" : ""}`}
          >
            <ChevronDown className="w-5 h-5 text-zinc-700 group-hover/norm:text-accent-gold-bright transition-colors" />
          </div>
        </div>
      </button>

      {expanded && (
        <div className="p-8 pt-0 animate-in slide-in-from-top-4 duration-500">
          <div className="h-px w-full bg-white/5 mb-8" />

          {(function renderContent() {
            const hasTranslation =
              explanation?.translation &&
              explanation.translation !== content &&
              /* skip bracketed fallback — e.g. "[§ 123 BGB]" when no API key */
              explanation.translation !== `[${content}]`;

            const isFallback =
              !!explanation?.translation &&
              explanation.translation !== content &&
              explanation.translation === `[${content}]`;

            /* per-mode explaining message */
            function explainingPill() {
              switch (settings.mode) {
                case "browser":
                case "basic":
                  return (
                    <span className="text-xs font-black uppercase tracking-widest text-zinc-600 flex items-center gap-2">
                      <Loader2 className="w-3 h-3 animate-spin" />
                      {t("norm.translating_browser")}
                    </span>
                  );
                case "cloud":
                  return (
                    <span className="text-xs font-black uppercase tracking-widest text-amber-600/80 flex items-center gap-2">
                      <Loader2 className="w-3 h-3 animate-spin" />
                      {t("norm.translating_cloud")}
                    </span>
                  );
                case "local":
                  return (
                    <span className="text-xs font-black uppercase tracking-widest text-amber-600/80 flex items-center gap-2">
                      <Loader2 className="w-3 h-3 animate-spin" />
                      {t("norm.translating_local")}
                    </span>
                  );
                default:
                  return (
                    <span className="text-xs font-black uppercase tracking-widest text-zinc-600 flex items-center gap-2">
                      <Loader2 className="w-3 h-3 animate-spin" />
                      {t("norm.translating")}
                    </span>
                  );
              }
            }

            return (
              <div className="legal-text whitespace-pre-wrap bg-white/[0.01] p-10 border border-white/5 relative">
                <div className="absolute top-0 left-0 w-8 h-8 border-t border-l border-white/10" />
                <div className="absolute bottom-0 right-0 w-8 h-8 border-b border-r border-white/10" />

                {/* Language badge + toggle */}
                <div className="flex items-center justify-between mb-6 min-h-5">
                  {showGerman ? (
                    <span className="text-xs font-black uppercase tracking-widest text-zinc-600">
                      {t("norm.german_original")}
                    </span>
                  ) : isFallback ? (
                    <span className="text-xs font-black uppercase tracking-widest text-amber-600/60 flex items-center gap-2">
                      {t("norm.translation_unavailable")}
                    </span>
                  ) : hasTranslation ? (
                    <span className="text-xs font-black uppercase tracking-widest text-accent-gold/60">
                      Translated to{" "}
                      {LANGUAGE_NAMES[settings.language] || "English"}
                    </span>
                  ) : explaining ? (
                    explainingPill()
                  ) : null}

                  {hasTranslation && (
                    <button
                      onClick={() => setShowGerman(!showGerman)}
                      className="text-xs font-black uppercase tracking-widest text-zinc-700 hover:text-accent-gold transition-colors active:scale-95"
                    >
                      {showGerman
                        ? t("norm.show_translation")
                        : t("norm.show_german")}
                    </button>
                  )}
                </div>

                {/* Content */}
                <p
                  className={
                    showGerman || !hasTranslation
                      ? "text-zinc-500 font-serif italic leading-relaxed"
                      : "text-zinc-200 font-sans font-medium leading-relaxed"
                  }
                >
                  {showGerman || isFallback
                    ? content
                    : hasTranslation
                      ? explanation!.translation
                      : content}
                </p>
              </div>
            );
          })()}

          <div className="mt-12">
            {!explanation ? (
              <div className="flex items-center gap-4 monumental-type opacity-40">
                {explaining ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-accent-gold" />
                    <span>{t("norm.analyzing")}</span>
                  </>
                ) : (
                  <FeatureGate
                    requirement="ai-mode"
                    message={t("norm.gate_translate")}
                    met={settings.mode !== "basic"}
                  >
                    <button
                      onClick={() => fetchExplanation()}
                      className="flex items-center gap-4 opacity-40 hover:opacity-100 hover:text-accent-gold transition-all duration-500 group/btn active:scale-95"
                    >
                      <Languages className="w-4 h-4 group-hover/btn:rotate-12 transition-transform" />
                      <span>
                        {t("norm.translate", {
                          lang: LANGUAGE_NAMES[settings.language] || "English",
                        })}
                      </span>
                    </button>
                  </FeatureGate>
                )}
              </div>
            ) : (
              <div className="space-y-10 animate-fade-in">
                {/* Translation */}
                <div className="p-8 glass-panel border-accent-gold/10 relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-1 h-full bg-accent-gold-bright opacity-40" />
                  <div className="flex items-center gap-3 monumental-type mb-6 opacity-60">
                    <Languages className="w-3.5 h-3.5" />
                    {explanation.is_official
                      ? t("norm.translation_official")
                      : t("norm.translation_ai")}
                  </div>
                  <p className="legal-text text-white font-sans font-medium leading-relaxed">
                    {explanation.translation}
                  </p>
                </div>

                {/* Grid for other insights */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {/* Summary — electric blue accent */}
                  <div className="p-6 border border-white/5 bg-zinc-950/40 relative group/insight spotlight-glow">
                    <div className="absolute top-0 left-0 w-1 h-1 bg-accent-electric opacity-40 group-hover/insight:opacity-100 transition-opacity" />
                    <div className="monumental-type opacity-20 mb-4 flex items-center gap-2 group-hover/insight:opacity-50 transition-opacity">
                      {t("norm.content_summary")}
                    </div>
                    <p className="text-sm text-zinc-500 leading-relaxed italic font-serif">
                      {explanation.summary}
                    </p>
                  </div>
                  {/* Context — neon purple accent */}
                  <div className="p-6 border border-white/5 bg-zinc-950/40 relative group/insight spotlight-glow">
                    <div className="absolute top-0 left-0 w-1 h-1 bg-accent-neon opacity-40 group-hover/insight:opacity-100 transition-opacity" />
                    <div className="monumental-type opacity-20 mb-4 flex items-center gap-2 group-hover/insight:opacity-50 transition-opacity">
                      {t("norm.content_context")}
                    </div>
                    <p className="text-sm text-zinc-500 leading-relaxed font-medium">
                      {explanation.implications}
                    </p>
                  </div>
                  {/* Steps — metallic gold accent */}
                  <div className="p-6 border border-accent-gold/10 bg-accent-gold/[0.02] relative group/insight spotlight-glow">
                    <div className="absolute top-0 left-0 w-1 h-1 bg-accent-gold opacity-40 group-hover/insight:opacity-100 transition-opacity" />
                    <div className="monumental-type opacity-30 mb-4 flex items-center gap-2 text-accent-gold-bright group-hover/insight:opacity-100 transition-opacity">
                      {t("norm.content_steps")}
                    </div>
                    <p className="text-sm text-zinc-400 leading-relaxed font-black uppercase tracking-wide">
                      {explanation.next_steps}
                    </p>
                  </div>
                </div>

                {/* Disclaimer */}
                <div className="flex justify-center">
                  <p className="text-xs font-black uppercase tracking-[0.4em] text-zinc-700 italic border-y border-white/5 py-4 px-10">
                    {t("norm.disclaimer")}
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
