"use client";

import { useState, useEffect, useCallback, startTransition } from "react";
import { Languages, Loader2, ChevronDown } from "lucide-react";
import {
  AppLanguage,
  LANGUAGE_NAMES,
  NormExplanation,
  ChatSettings,
  DEFAULT_CHAT_SETTINGS,
} from "../lib/types";
import { toast } from "sonner";
import { translateText } from "../lib/translate";

const STORAGE_KEY = "glv_chat_settings";

interface NormViewerProps {
  normId: string;
  lawKey: string;
  title: string;
  content: string;
}

export default function NormViewer({
  normId,
  lawKey,
  title,
  content,
}: NormViewerProps) {
  const [expanded, setExpanded] = useState(false);
  const [explanation, setExplanation] = useState<NormExplanation | null>(null);
  const [explaining, setExplaining] = useState(false);
  const [settings, setSettings] = useState<ChatSettings>(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        return { ...DEFAULT_CHAT_SETTINGS, ...JSON.parse(raw) };
      }
    } catch {}
    return DEFAULT_CHAT_SETTINGS;
  });
  const fetchExplanation = useCallback(async () => {
    if (explanation || explaining) return;
    setExplaining(true);
    try {
      if (settings.mode === "local") {
        // CLIENT-SIDE EXPLAIN FOR LOCAL MODE
        const langName = LANGUAGE_NAMES[settings.language] || "English";
        const explainPrompt = `Explain this German law section. Respond in ${langName}.\n\nGerman text: ${content}\n\nReturn STRICT JSON with these exact fields:\n{\n  "translation": "accurate legal translation of the German text",\n  "summary": "what this means in simple terms in the user's language",\n  "implications": "what this means practically for the person involved",\n  "next_steps": "concrete recommended actions"\n}`;

        const brokerRes = await fetch(`${settings.brokerUrl}/api/chat`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            message: explainPrompt,
            context: content,
            model: settings.ollamaModel || undefined,
            language: langName,
            temperature: 0.3,
            max_tokens: 2048,
          }),
        });

        if (!brokerRes.ok) throw new Error("Local broker failure");
        const localData = await brokerRes.json();

        let jsonStr = localData.response.trim();
        const codeBlockMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)```/);
        if (codeBlockMatch) jsonStr = codeBlockMatch[1].trim();

        let parsed;
        try {
          parsed = JSON.parse(jsonStr);
        } catch {
          parsed = {
            translation: jsonStr,
            summary: jsonStr,
            implications: jsonStr,
            next_steps: jsonStr,
          };
        }

        setExplanation({
          norm_id: normId,
          law_key: lawKey,
          law_title: title,
          lang: settings.language,
          translation: parsed.translation || "",
          summary: parsed.summary || "",
          implications: parsed.implications || "",
          next_steps: parsed.next_steps || "",
          disclaimer: "Generated by Local AI.",
        });
        return;
      }

      // BASIC MODE — use client-side translation worker (no API key needed)
      if (settings.mode === "basic") {
        const langName = LANGUAGE_NAMES[settings.language] || "English";
        let translation = "";
        try {
          translation = await translateText(content, {
            sourceLang: "de",
            targetLang:
              settings.language === "de" ? "en" : settings.language || "en",
          });
        } catch {
          translation = content; // fall back to raw German if worker fails
        }
        setExplanation({
          norm_id: normId,
          law_key: lawKey,
          law_title: title,
          lang: settings.language,
          translation: translation,
          summary:
            langName !== "English"
              ? "Browser AI translation — consult a licensed German attorney."
              : "Browser AI translation — not legally binding.",
          implications:
            "See a licensed German attorney (Rechtsanwalt) for legally binding advice on your specific situation.",
          next_steps: "Consult a Rechtsanwalt for your specific situation.",
          disclaimer: "Generated by browser AI (client-side).",
        });
        return;
      }

      // CLOUD MODES
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          normId,
          lawKey,
          lawTitle: title,
          content,
          lang: settings.language,
          mode: settings.mode === "browser" ? "cloud" : settings.mode,
          provider: settings.provider,
          model: settings.model,
          customEndpoint: settings.customEndpoint,
          brokerUrl: settings.brokerUrl,
          ollamaModel: settings.ollamaModel,
          ollamaParams: settings.ollamaParams,
        }),
      });
      if (!res.ok) throw new Error("Explanation failed");
      const data = (await res.json()) as NormExplanation;
      setExplanation(data);
    } catch (err) {
      console.error("Norm explain failed:", err);
      if (settings.mode === "local") {
        toast.error(
          "Local AI unavailable. Check if Ollama is running and the broker URL is correct.",
        );
      } else {
        toast.error("Explanation failed. Check settings.");
      }
    } finally {
      setExplaining(false);
    }
  }, [explanation, explaining, settings, normId, lawKey, title, content]);

  // Auto-fetch translation when the norm is expanded
  useEffect(() => {
    if (expanded) {
      // Use startTransition to avoid synchronous setState in effect (React hooks rule)
      startTransition(() => {
        fetchExplanation();
      });
    }
  }, [expanded, fetchExplanation]);

  return (
    <div className="premium-card overflow-hidden mb-6 group/norm border-white/5 bg-zinc-950/20">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between p-8 text-left hover:bg-white/[0.01] transition-all duration-500 relative"
      >
        <div className="flex-1">
          <span className="text-accent-gold-body font-black mr-6 text-xs tracking-[0.3em] uppercase opacity-60">
            Section {normId}
          </span>
          <span className="font-serif font-bold text-white text-xl tracking-tight">
            {title}
          </span>
        </div>
        <div className="flex items-center gap-6">
          <div
            className={`p-2 transition-transform duration-500 ${expanded ? "rotate-180" : ""}`}
          >
            <ChevronDown className="w-5 h-5 text-zinc-700 group-hover/norm:text-accent-gold transition-colors" />
          </div>
        </div>
      </button>

      {expanded && (
        <div className="p-8 pt-0 animate-in slide-in-from-top-4 duration-500">
          <div className="h-px w-full bg-white/5 mb-8" />
          <div className="legal-text text-zinc-400 whitespace-pre-wrap font-serif italic bg-white/[0.01] p-10 border border-white/5 relative">
            <div className="absolute top-0 left-0 w-8 h-8 border-t border-l border-white/10" />
            <div className="absolute bottom-0 right-0 w-8 h-8 border-b border-r border-white/10" />
            {content}
          </div>

          <div className="mt-12">
            {!explanation ? (
              <div className="flex items-center gap-4 monumental-type opacity-40">
                {explaining ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-accent-gold" />
                    <span>Decrypting Dialect...</span>
                  </>
                ) : (
                  <button
                    onClick={() => fetchExplanation()}
                    className="flex items-center gap-4 opacity-40 hover:opacity-100 hover:text-accent-gold transition-all duration-500 group/btn active:scale-95"
                  >
                    <Languages className="w-4 h-4 group-hover/btn:rotate-12 transition-transform" />
                    <span>Retry Translation</span>
                  </button>
                )}
              </div>
            ) : (
              <div className="space-y-10 animate-fade-in">
                {/* Translation */}
                <div className="p-8 glass-panel border-white/10 relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-1 h-full bg-accent-gold-bright opacity-30" />
                  <div className="flex items-center gap-3 monumental-type mb-6 opacity-60">
                    <Languages className="w-3.5 h-3.5" />
                    {explanation.is_official
                      ? "Official Translation"
                      : "Vernacular Translation"}
                  </div>
                  <p className="legal-text text-white font-sans font-medium leading-relaxed">
                    {explanation.translation}
                  </p>
                </div>

                {/* Grid for other insights */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="p-6 border border-white/5 bg-zinc-950/40 relative group/insight">
                    <div className="monumental-type opacity-20 mb-4 flex items-center gap-2 group-hover/insight:opacity-50 transition-opacity">
                      Summary
                    </div>
                    <p className="text-sm text-zinc-500 leading-relaxed italic font-serif">
                      {explanation.summary}
                    </p>
                  </div>
                  <div className="p-6 border border-white/5 bg-zinc-950/40 relative group/insight">
                    <div className="monumental-type opacity-20 mb-4 flex items-center gap-2 group-hover/insight:opacity-50 transition-opacity">
                      Context
                    </div>
                    <p className="text-sm text-zinc-500 leading-relaxed font-medium">
                      {explanation.implications}
                    </p>
                  </div>
                  <div className="p-6 border border-accent-gold/10 bg-accent-gold/[0.02] relative group/insight">
                    <div className="absolute top-0 left-0 w-1 h-1 bg-accent-gold opacity-40" />
                    <div className="monumental-type opacity-30 mb-4 flex items-center gap-2 text-accent-gold-bright group-hover/insight:opacity-100 transition-opacity">
                      Steps
                    </div>
                    <p className="text-sm text-zinc-400 leading-relaxed font-black uppercase tracking-wide">
                      {explanation.next_steps}
                    </p>
                  </div>
                </div>

                {/* Disclaimer */}
                <div className="flex justify-center">
                  <p className="text-xs font-black uppercase tracking-[0.4em] text-zinc-700 italic border-y border-white/5 py-4 px-10">
                    Vault Intelligence — Preliminary Non-Binding Report
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
