/**
 * Category Detection Module
 *
 * Automatically detects the legal category of a user query by matching
 * English and German keywords against known legal categories.
 * Used to filter Qdrant search results to the relevant category,
 * eliminating noise from unrelated domains (e.g., maritime law in a
 * "car accident" query).
 */

// ── Category Keyword Maps ──────────────────────────────────────────────────

interface CategoryEntry {
  keywords: string[];
  weight: number; // relative importance (higher = stronger signal)
}

const CATEGORY_KEYWORDS: Record<string, CategoryEntry> = {
  traffic: {
    weight: 1.0,
    keywords: [
      // German
      "verkehrsunfall",
      "autounfall",
      "verkehrsverstoß",
      "geschwindigkeitsüberschreitung",
      "fahrverbot",
      "führerschein",
      "bußgeldbescheid",
      "knöllchen",
      "fahrerflucht",
      "trunkenheit",
      "fahruntüchtigkeit",
      "straßenverkehr",
      "verkehrsrecht",
      "kraftfahrzeug",
      "kfz",
      "fahrerlaubnis",
      "punkte flensburg",
      "verkehrssünde",
      "stvg",
      "stvo",
      "owig",
      "verkehr",
      "fußgänger",
      "radfahrer",
      "abschleppen",
      "panne",
      "hauptuntersuchung",
      "tüv",
      "kfz-steuer",
      "fahrzeugzulassung",
      "verkehrszeichen",
      "unfall",
      "fahrrad",
      "autobahn",
      "geschwindigkeit",
      // English
      "car accident",
      "traffic accident",
      "accident",
      "suspended license",
      "speeding ticket",
      "parking ticket",
      "driving ban",
      "drivers license",
      "driver's license",
      "drunk driving",
      "dui",
      "dwi",
      "red light",
      "traffic violation",
      "speeding",
      "driving",
      "driver",
      "license suspension",
      "road traffic",
      "hit and run",
      "property damage car",
      "car insurance",
      "vehicle registration",
      "car tax",
      "inspection",
      "tuv",
      "speeding fine",
      "traffic ticket",
      "car crash",
      "collision",
      "driving without",
      "parking",
      "towing",
      "breakdown",
      "roadside assistance",
      "traffic rules",
      "highway",
    ],
  },
  criminal: {
    weight: 1.0,
    keywords: [
      // German
      "strafrecht",
      "straftat",
      "strafanzeige",
      "strafverfahren",
      "stgb",
      "diebstahl",
      "raub",
      "körperverletzung",
      "betrug",
      "untreue",
      "strafverteidigung",
      "notwehr",
      "staatsanwaltschaft",
      "ermittlungsverfahren",
      "durchsuchung",
      "beschlagnahme",
      "strafgesetzbuch",
      "strafprozessordnung",
      "stpo",
      "rechtsbeugung",
      "freiheitsberaubung",
      "nötigung",
      "schwere körperverletzung",
      "gefährliche körperverletzung",
      "sachbeschädigung",
      "hausfriedensbruch",
      "urkundenfälschung",
      "unterschlagung",
      "hehlerei",
      "begünstigung",
      "geldwäsche",
      "bestechung",
      "bestechlichkeit",
      "polizei",
      "festnahme",
      "haftbefehl",
      "untersuchungshaft",
      "kaution",
      "bewährung",
      "geldstrafe",
      "freiheitsstrafe",
      "anklage",
      "verteidiger",
      "pflichtverteidiger",
      "vorstrafe",
      "führungszeugnis",
      "strafregister",
      // English
      "theft",
      "stolen",
      "stole",
      "steal",
      "stealing",
      "thief",
      "pickpocket",
      "wallet",
      "purse",
      "assault",
      "assaulted",
      "battery",
      "fraud",
      "embezzlement",
      "robbery",
      "burglary",
      "criminal",
      "crime",
      "criminal offense",
      "press charges",
      "criminal complaint",
      "criminal proceedings",
      "criminal defense",
      "evidence",
      "witness",
      "search warrant",
      "arrest",
      "bail",
      "probation",
      "fine",
      "prison",
      "jail",
      "imprisonment",
      "suspended sentence",
      "criminal record",
      "police",
      "indictment",
      "verdict",
      "sentence",
      "self-defense",
      "money laundering",
      "drug offense",
      "drugs",
    ],
  },
  family: {
    weight: 1.0,
    keywords: [
      // German
      "scheidung",
      "trennung",
      "sorgerecht",
      "umgangsrecht",
      "kindesunterhalt",
      "unterhalt",
      "ehegattenunterhalt",
      "nachehelicher unterhalt",
      "ehe",
      "eheschließung",
      "lebenspartnerschaft",
      "adoption",
      "elternzeit",
      "elterngeld",
      "kindergeld",
      "vaterschaft",
      "vormundschaft",
      "namensänderung",
      "häusliche gewalt",
      "schutzanordnung",
      "gewaltschutz",
      "familienrecht",
      "versorgungsausgleich",
      "zugewinn",
      "zugewinnausgleich",
      "ehevertrag",
      "trennungvereinbarung",
      "scheidungsfolgen",
      "kind",
      "kinder",
      "eltern",
      "mutter",
      "vater",
      // English
      "divorce",
      "divorced",
      "separation",
      "custody",
      "child support",
      "alimony",
      "spousal support",
      "maintenance",
      "marriage",
      "wedding",
      "civil partnership",
      "adoption",
      "foster care",
      "parental leave",
      "parental allowance",
      "child benefit",
      "paternity",
      "guardianship",
      "name change",
      "domestic violence",
      "protection order",
      "restraining order",
      "prenup",
      "prenuptial",
      "visitation rights",
      "joint custody",
    ],
  },
  labor: {
    weight: 1.0,
    keywords: [
      // German
      "kündigung",
      "kündigungsschutz",
      "kündigungsfrist",
      "arbeitsrecht",
      "arbeitsvertrag",
      "arbeitgeber",
      "arbeitnehmer",
      "betriebsrat",
      "tarifvertrag",
      "mindestlohn",
      "überstunden",
      "urlaub",
      "urlaubsanspruch",
      "abfindung",
      "abmahnung",
      "probezeit",
      "befristet",
      "teilzeit",
      "elternzeit",
      "krankmeldung",
      "krankheitstag",
      "lohn",
      "gehalt",
      "vergütung",
      "zeugnissprache",
      "arbeitszeugnis",
      "wettbewerbsverbot",
      "sozialplan",
      "betriebsvereinbarung",
      "gleitzeit",
      "schichtarbeit",
      "bereitschaftsdienst",
      "rufbereitschaft",
      "elternzeit",
      "mutterschutz",
      "beschäftigungsverbot",
      "kündigungsschutzklage",
      "kündigungsgrund",
      // English
      "fire",
      "fired",
      "firing",
      "fires",
      "dismissal",
      "wrongful dismissal",
      "employer",
      "employee",
      "employment",
      "employment contract",
      "labor law",
      "works council",
      "collective agreement",
      "minimum wage",
      "overtime",
      "holiday",
      "vacation",
      "annual leave",
      "sick day",
      "part-time",
      "fixed-term",
      "probation period",
      "notice period",
      "severance",
      "reference letter",
      "non-compete",
      "termination",
      "layoff",
      "unfair dismissal",
      "redundant",
      "redundancy",
      "salary",
      "wage",
    ],
  },
  housing: {
    weight: 1.0,
    keywords: [
      // German
      "mietminderung",
      "mietvertrag",
      "mieter",
      "vermieter",
      "miete",
      "mieterhöhung",
      "mietpreisbremse",
      "betriebskosten",
      "nebenkosten",
      "heizkosten",
      "kaution",
      "räumung",
      "untervermietung",
      "wohnung",
      "schimmel",
      "modernisierung",
      "wohnrecht",
      "mietrecht",
      "wohnfläche",
      "instandhaltung",
      "instanthaltung",
      "gebrauch",
      "mangel wohnung",
      "mietmangel",
      "wohnungsmangel",
      "nachbar",
      "lärmbelästigung",
      " renovierung",
      "bau",
      "baugenehmigung",
      "wohnungseigentum",
      "eigentumswohnung",
      "wohnungstür",
      "haustür",
      "keller",
      "dachboden",
      "garten",
      "balkon",
      "terrasse",
      "heizung",
      "warmwasser",
      "strom",
      "wasser",
      "haustier",
      "hund",
      "katze",
      "tiere in der wohnung",
      // English
      "rent reduction",
      "landlord",
      "tenant",
      "deposit return",
      "deposit",
      "rent increase",
      "rent cap",
      "operating costs",
      "utilities",
      "heating costs",
      "security deposit",
      "eviction",
      "lease agreement",
      "subletting",
      "apartment",
      "condominium",
      "renovation",
      "modernization",
      "mold",
      "noise complaint",
      "neighbor",
      "construction",
      "building permit",
      "rental agreement",
      "rent",
      "leasing",
      "housing",
      "lease",
      "move out",
      "moving out",
    ],
  },
  consumer: {
    weight: 1.0,
    keywords: [
      // German
      "gewährleistung",
      "widerruf",
      "widerrufsrecht",
      "verbraucherschutz",
      "mangel",
      "sachmangel",
      "garantie",
      "kaufvertrag",
      "kaufpreis",
      "fernabsatz",
      "rücktritt",
      "rücktrittsrecht",
      "minderung",
      "verbraucher",
      "agb",
      "allgemeine geschäftsbedingungen",
      "rechnung",
      "mahnung",
      "mahnverfahren",
      "inkasso",
      "produkthaftung",
      "rückruf",
      "rückerstattung",
      "rücksendung",
      "nachbesserung",
      "ersatzlieferung",
      "kauf",
      "online-kauf",
      "internet",
      "bestellung",
      "lieferung",
      "vertrag",
      "vertragsstrafe",
      "verzug",
      "privatinsolvenz",
      "insolvenz",
      "verbraucherinsolvenz",
      "schufa",
      "bonität",
      "kreditwürdigkeit",
      // English
      "warranty",
      "refund",
      "return",
      "defective",
      "defect",
      "consumer protection",
      "consumer",
      "withdrawal",
      "right of withdrawal",
      "cancellation policy",
      "defective product",
      "guarantee",
      "purchase price",
      "purchase contract",
      "sales contract",
      "distance selling",
      "online purchase",
      "digital content",
      "product liability",
      "recall",
      "repair",
      "replacement",
      "price reduction",
      "general terms",
      "terms and conditions",
      "debt collection",
      "dunning letter",
      "collection agency",
      "insolvency",
      "bankruptcy",
      "private insolvency",
      "debt relief",
      "foreclosure",
    ],
  },
  social: {
    weight: 1.0,
    keywords: [
      // German
      "krankenversicherung",
      "gesetzliche krankenversicherung",
      "gkv",
      "private krankenversicherung",
      "pkv",
      "pflegeversicherung",
      "pflegegrad",
      "pflege",
      "rente",
      "rentenversicherung",
      "altersrente",
      "erwerbsminderungsrente",
      "sozialhilfe",
      "bürgergeld",
      "arbeitslosengeld",
      "alg",
      "krankengeld",
      "krankenhaus",
      "krankenkasse",
      "unfallversicherung",
      "rehabilitation",
      "reha",
      "sozialgericht",
      "sozialrecht",
      "sozialgesetzbuch",
      "sgb",
      "behinderung",
      "schwerbehinderung",
      "schwerbehindertenausweis",
      "mutterschutz",
      "mutterschaftsgeld",
      "elterngeld",
      "wohngeld",
      "kindergeld",
      "kinderzuschlag",
      "arbeitslos",
      "arbeitssuchend",
      "jobcenter",
      "agentur für arbeit",
      "grundsicherung",
      "sozialamt",
      "krankheit",
      "krank",
      "arzt",
      "ärztliche behandlung",
      "zahnarzt",
      "krankenhausaufenthalt",
      "medikamente",
      // English
      "health insurance",
      "statutory health insurance",
      "private health insurance",
      "long-term care insurance",
      "nursing care",
      "care insurance",
      "pension",
      "retirement",
      "old-age pension",
      "disability",
      "disabled",
      "sick leave",
      "sick note",
      "medical certificate",
      "incapacity to work",
      "rehabilitation",
      "unemployment",
      "unemployment benefit",
      "citizen's benefit",
      "welfare",
      "housing benefit",
      "maternity leave",
      "maternity benefit",
      "sick pay",
      "accident insurance",
      "social security",
      "hartz",
      "job center",
    ],
  },
  finance: {
    weight: 1.0,
    keywords: [
      // German
      "steuererklärung",
      "einkommensteuer",
      "umsatzsteuer",
      "mehrwertsteuer",
      "steuerbescheid",
      "steuerberater",
      "steuerhinterziehung",
      "steuerstrafverfahren",
      "körperschaftsteuer",
      "gewerbesteuer",
      "grundsteuer",
      "erbschaftsteuer",
      "schenkungsteuer",
      "freibetrag",
      "steuerfreibetrag",
      "steuerabzug",
      "steuerfrei",
      "betriebsprüfung",
      "steuer",
      "darlehen",
      "kredit",
      "hypothek",
      "grundschuld",
      "insolvenz",
      "privatinsolvenz",
      "kapitalanlage",
      "aktie",
      "wertpapiere",
      "fonds",
      "zinsen",
      "zins",
      "anlage",
      "investment",
      "geldwäsche",
      "kontopfändung",
      "schulden",
      "umsatzsteuervoranmeldung",
      "vorsteuer",
      // English
      "tax",
      "income tax",
      "value added tax",
      "sales tax",
      "vat",
      "corporate tax",
      "trade tax",
      "property tax",
      "inheritance tax",
      "gift tax",
      "tax return",
      "tax assessment",
      "tax deduction",
      "allowance",
      "tax-free",
      "tax advisor",
      "tax audit",
      "tax evasion",
      "interest",
      "loan",
      "mortgage",
      "credit",
      "investment",
      "securities",
      "stock",
      "capital gains",
      "insolvency",
      "bankruptcy",
      "debt",
      "foreclosure",
      "money laundering",
    ],
  },
  public: {
    weight: 1.0,
    keywords: [
      // German
      "verwaltungsakt",
      "behörde",
      "verwaltungsgericht",
      "verwaltungsrecht",
      "verwaltungsgerichtsordnung",
      "vwgo",
      "einbürgerung",
      "staatsangehörigkeit",
      "aufenthalt",
      "aufenthaltserlaubnis",
      "niederlassungserlaubnis",
      "visum",
      "asyl",
      "asylrecht",
      "flüchtling",
      "abschiebung",
      "duldung",
      "einwanderung",
      "integrationskurs",
      "integrationsgesetz",
      "beamter",
      "öffentlicher dienst",
      "amtshaftung",
      "datenschutz",
      "datenschutzgrundverordnung",
      "dsgvo",
      "informationsfreiheit",
      "bdsg",
      "widerspruch",
      "widerspruchsverfahren",
      "grundgesetz",
      "gg",
      "grundrecht",
      "grundrechte",
      "menschenrecht",
      "petition",
      "wahlrecht",
      "bverfg",
      "bundesverfassungsgericht",
      "ordnungswidrigkeit",
      "owig",
      "pass",
      "personalausweis",
      "meldegesetz",
      "versammlungsrecht",
      "vereinsrecht",
      // English
      "administrative act",
      "administrative court",
      "authority",
      "government agency",
      "public office",
      "official",
      "citizenship",
      "naturalization",
      "residence",
      "residence permit",
      "settlement permit",
      "visa",
      "asylum",
      "refugee",
      "deportation",
      "immigration",
      "integration course",
      "public service",
      "civil servant",
      "freedom of information",
      "data protection",
      "data privacy",
      "gdpr",
      "privacy",
    ],
  },
  tech: {
    weight: 0.8,
    keywords: [
      // German
      "umweltrecht",
      "immissionsschutz",
      "bundesimmissionsschutzgesetz",
      "bimschg",
      "naturschutz",
      "bundesnaturschutzgesetz",
      "wassergesetz",
      "wasserhaushaltsgesetz",
      "whg",
      "kreislaufwirtschaft",
      "abfall",
      "abfallrecht",
      "energie",
      "erneuerbare energien",
      "eeg",
      "energiewirtschaftsgesetz",
      "enwg",
      "telekommunikation",
      "telekommunikationsgesetz",
      "tkg",
      "digitalisierung",
      "digitale dienste",
      "digitale infrastruktur",
      "künstliche intelligenz",
      "ki",
      "elektromobilität",
      "ladeinfrastruktur",
      "netzausbau",
      "breitband",
      "umwelt",
      "klimaschutz",
      "klima",
      // English
      "environment",
      "environmental law",
      "emissions",
      "nature protection",
      "water law",
      "circular economy",
      "waste management",
      "renewable energy",
      "solar",
      "wind power",
      "energy law",
      "telecommunications",
      "digital",
      "digital services",
      "artificial intelligence",
      "ai",
      "data center",
      "electric mobility",
      "ev charging",
      "climate",
      "climate protection",
      "broadband",
    ],
  },
  berlin: {
    weight: 0.7,
    keywords: [
      // German — Berlin-specific laws often use "BLN" prefix or contain "Berlin"
      "berlin",
      "berliner",
      "bln",
      "senatsverwaltung",
      "berliner betriebe",
      "berliner stadtrecht",
      "berlin spezifisch",
      "landesrecht berlin",
      "berliner gesetz",
      "berliner verordnung",
      "senat von berlin",
      // English
      "berlin",
      "berlin law",
    ],
  },
};

// ── Detection Logic ─────────────────────────────────────────────────────────

interface CategoryMatch {
  category: string;
  score: number;
  matchedTerms: string[];
}

/**
 * Detect the most likely legal category for a given query string.
 *
 * Strategy:
 * 1. Collect all keyword matches per category (case-insensitive, partial match)
 * 2. Score each category based on number of unique matched terms × category weight
 * 3. Normalize by query length (to avoid bias from long queries with many words)
 * 4. Only return a category if confidence exceeds the threshold (default 30%)
 *
 * @param query - The user's search or chat query (English or German)
 * @param threshold - Confidence threshold 0-1 (default 0.3, higher = stricter)
 * @returns The detected category string, or undefined if confidence is too low
 */
export function detectCategory(
  query: string,
  threshold: number = 0.2,
): string | undefined {
  if (!query || query.trim().length < 3) return undefined;

  const lower = query.toLowerCase().trim();
  const words = lower.split(/\s+/).filter((w) => w.length > 0);
  const queryLength = words.length;

  // Score each category
  const results: CategoryMatch[] = [];
  const queryWords = words.length;

  for (const [category, entry] of Object.entries(CATEGORY_KEYWORDS)) {
    const matchedTerms: string[] = [];

    for (const kw of entry.keywords) {
      if (lower.includes(kw.toLowerCase())) {
        matchedTerms.push(kw);
      }
    }

    if (matchedTerms.length > 0) {
      // Score based on unique matched keywords / sqrt(query word count)
      // Using sqrt prevents long chat queries (12+ words) from drowning out the signal.
      // Short query "car accident" = 2/1.41 = 1.0 (capped); long query "i got into a car
      // accident in germany..." = 2/3.46 = 0.578. Without sqrt, the long query scores
      // 2/12 = 0.167, which typically falls below the 0.2 threshold.
      const uniqueKeywordScore = Math.min(
        1.0,
        matchedTerms.length / Math.max(Math.sqrt(queryWords), 1),
      );

      // Boost if matched keywords cover many characters (redundancy bonus)
      const matchedChars = new Set<number>();
      for (const kw of matchedTerms) {
        const kwLower = kw.toLowerCase();
        let idx = lower.indexOf(kwLower);
        while (idx !== -1) {
          for (let i = idx; i < idx + kwLower.length; i++) {
            matchedChars.add(i);
          }
          idx = lower.indexOf(kwLower, idx + 1);
        }
      }
      const coverage = matchedChars.size / Math.max(lower.length, 1);

      // Final score: density × weight, boosted by coverage
      // Coverage uses log-like scaling: short keywords in long queries
      // shouldn't be penalized as much as raw ratio suggests
      const coverageBoost = 0.5 + Math.min(1.0, coverage * 3) * 0.5;
      const score = uniqueKeywordScore * entry.weight * coverageBoost;

      results.push({
        category,
        score,
        matchedTerms,
      });
    }
  }

  if (results.length === 0) return undefined;

  // Sort by score descending
  results.sort((a, b) => b.score - a.score);

  const top = results[0];
  const secondScore = results.length > 1 ? results[1].score : 0;

  // Require a clear margin over the second-place category
  // This prevents ambiguous results (e.g., "I want to buy a car" matching both traffic and consumer)
  const margin = top.score > 0 ? (top.score - secondScore) / top.score : 1;

  // Base requirement: score must meet the threshold
  if (top.score < threshold) {
    console.log(
      `[CategoryDetect] "${query}" → none ` +
        `(best: ${top.category} at ${top.score.toFixed(3)} < threshold ${threshold})`,
    );
    return undefined;
  }

  // For close races (margin < 50%), require a higher bar
  if (margin < 0.5) {
    const boostedThreshold = threshold + (1 - threshold) * (1 - margin * 2);
    if (top.score < boostedThreshold) {
      console.log(
        `[CategoryDetect] "${query}" → none ` +
          `(best: ${top.category} at ${top.score.toFixed(3)} < boosted ${boostedThreshold.toFixed(3)}, ` +
          `margin: ${(margin * 100).toFixed(0)}%)`,
      );
      return undefined;
    }
  }

  console.log(
    `[CategoryDetect] "${query}" → ${top.category} ` +
      `(score: ${top.score.toFixed(3)}, threshold: ${threshold}, ` +
      `margin: ${(margin * 100).toFixed(0)}%, matches: ${top.matchedTerms.join(", ")})`,
  );
  return top.category;
}

/**
 * Returns all available category keys for reference.
 */
export function getAllCategories(): string[] {
  return Object.keys(CATEGORY_KEYWORDS).filter((k) => k !== "other");
}

/**
 * Returns the supported category list (for display / UI).
 */
export const CATEGORIES = [
  { key: "traffic", label: "Traffic & Transport" },
  { key: "criminal", label: "Criminal Law" },
  { key: "family", label: "Family & Life" },
  { key: "labor", label: "Labor & Career" },
  { key: "housing", label: "Housing & Rent" },
  { key: "consumer", label: "Consumer Rights" },
  { key: "social", label: "Health & Social" },
  { key: "finance", label: "Taxes & Finance" },
  { key: "public", label: "Public & Rights" },
  { key: "tech", label: "Tech & Environment" },
  { key: "berlin", label: "Berlin Specific" },
  { key: "other", label: "Other" },
] as const;
