const { chromium } = require('@playwright/test');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 1800 } });
  const page = await context.newPage();
  const log = (msg) => console.log(msg);

  try {
    log('Step 1: Setting up Local AI mode...');
    await page.goto('http://localhost:3000/settings');
    await page.waitForSelector('text=Local AI', { timeout: 10000 });
    // Click the Local AI button (it might be the first one)
    await page.click('button:has-text("Local AI")');
    log('Switched to Local AI mode');
    await page.screenshot({ path: 'outputs/feature_test/settings_active.png' });

    log('Step 2: Searching for statute...');
    await page.goto('http://localhost:3000');
    const searchInput = page.getByPlaceholder(/SEARCH STATUTES BY KEYWORD/i);
    await searchInput.fill('Schadensersatzpflicht');
    await page.keyboard.press('Enter');

    await page.waitForURL(/q=Schadensersatzpflicht/i);
    log('Search results page loaded');
    await page.screenshot({ path: 'outputs/feature_test/search_results.png' });

    log('Step 3: Expanding section...');
    // Use force:true to bypass the absolute link overlay
    await page.click('text=§ 823', { force: true });
    await page.waitForSelector('text=Wer vorsätzlich oder fahrlässig', { timeout: 15000 });
    await page.screenshot({ path: 'outputs/feature_test/section_content.png' });
    log('Section content visible');

    log('Step 4: Testing AI Analysis...');
    await page.goto('http://localhost:3000');
    const analysisToggle = page.getByRole('button', { name: /AI ANALYSIS/i });
    await analysisToggle.click();

    const chatInput = page.getByPlaceholder(/DESCRIBE YOUR LEGAL SITUATION/i);
    await chatInput.fill('What happens if I break someone else property?');
    await page.keyboard.press('Enter');

    log('Waiting for AI response...');
    await page.waitForURL(/\/chat\?q=/);
    // In Local AI mode, wait for the response or specific text
    await page.waitForSelector('text=Generated by', { timeout: 120000 });
    await page.screenshot({ path: 'outputs/feature_test/ai_final_verified.png' });
    log('AI Analysis verified');

    log('All tests passed successfully!');
  } catch (err) {
    log('Test failed: ' + err.message);
    await page.screenshot({ path: 'outputs/feature_test/failure.png' });
  } finally {
    await browser.close();
  }
})();
