import { test, expect } from '@playwright/test';

test('Full flow: search, read, translate, analyze', async ({ page }) => {
  // 1. Go to home page
  await page.goto('http://localhost:3000');
  await expect(page).toHaveTitle(/German Law Vault/);

  // 2. Search for BGB § 823
  const searchInput = page.getByPlaceholder(/Search laws/i);
  await searchInput.fill('BGB 823');
  await page.keyboard.press('Enter');

  // 3. Verify search results
  await expect(page).toHaveURL(/\/search\?q=BGB\+823/);
  await expect(page.getByText(/Schadensersatzpflicht/i)).toBeVisible();

  // 4. Click to expand
  await page.getByText(/Schadensersatzpflicht/i).click();
  await expect(page.getByText(/Wer vorsätzlich oder fahrlässig/i)).toBeVisible();

  // 5. Trigger translation (if not automatic)
  // Check if "Translate to English" button exists
  const translateBtn = page.getByRole('button', { name: /Translate to/i });
  if (await translateBtn.isVisible()) {
    await translateBtn.click();
  }

  // Wait for translation (look for disclaimer or specific English text)
  await expect(page.getByText(/Disclaimer:/i)).toBeVisible({ timeout: 15000 });
  console.log('Translation verified');

  // 6. Switch to Analyze mode
  await page.goto('http://localhost:3000');
  const toggle = page.getByRole('button', { name: /Statute Search|AI Analysis/i });
  // If it's on Search, click to switch to Analyze
  const toggleText = await toggle.innerText();
  if (toggleText.includes('Statute Search')) {
     await toggle.click();
  }

  // 7. Ask a question
  await searchInput.fill('What happens if I break someone else property?');
  await page.keyboard.press('Enter');

  // 8. Verify Chat/Analyze results
  await expect(page).toHaveURL(/\/chat\?q=/);
  // Wait for AI response (look for "Generated by" footer or disclaimer)
  await expect(page.getByText(/Generated by/i)).toBeVisible({ timeout: 30000 });
  await expect(page.getByText(/§ 823/)).toBeVisible();

  console.log('Analysis verified');
});
